---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: docintel
  labels:
    app.kubernetes.io/instance: docintel
    app.kubernetes.io/component: service
    app.kubernetes.io/name: webapp
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: webapp
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: pod
    app.kubernetes.io/name: webapp
    app.kubernetes.io/part-of: docintel
